### PR TITLE
Note that initialization is optional if the default environment variables are used

### PR DESCRIPTION
**Pull request by wearhere**

### CODE REVIEW

**Comment by wearhere** [comment]
@ttacon can you give the Mixmax Employees team admin access to the repo please?

**Comment by wearhere** [comment]
Not sure why the tests are failing… Travis says "no environment variables" set so maybe it's this exact issue? 😆

**Comment by bradvogel** [comment]
I gave access to the team

**Comment by wearhere** [comment]
Fixing the tests

**Pull request merged**
