### PR TITLE
Clear summary on shutdown

### PR DESCRIPTION
**Pull request by Nevon**
#### Changes Made

Adds handling for summary metrics to `shutdown` method. Also adds some rudimentary testing of shutdown.

#### Potential Risks

I don't see any significant risks. I'm running this branch in my own service and it seems to be fine.

#### Test Plan

The tests are passing, including new tests, and it seems to run fine in production.

#### Checklist
- [x] I've increased test coverage
- [x] Since this is a public repository, I've checked I'm not publishing private data in the code, commit comments, or this PR.

### CODE REVIEW

**Comment by triwats** [comment]
I think this needs reviewing and looking at to be considered a candidate. This is a necessary improvement.

**Comment by reischapa** [comment]
@Nevon @triwats @ttacon 

+1 for this fix. I was actually about to submit a similar pull request, and then noticed this one existed.

**Comment by bradvogel** [comment]
Thanks. Due to an issue with our CI system (it apparently missed this PR), I had to open a new branch: https://github.com/mixmaxhq/cloudwatch-metrics/pull/40. Closing this one.

**Comment by bradvogel** [comment]
This was merged with https://github.com/mixmaxhq/cloudwatch-metrics/pull/40.

Thanks for the contribution and sorry for the delay!

**Pull request closed without merging**
